services:
  rtsproxy:
    image: ghcr.io/plsy1/rtsproxy
    container_name: rtsproxy
    ports:
      - 8554:8554
    restart: always
    # command: "--enable-nat" # 在此处添加启动参数，如 --enable-nat 或 -r 8192
    # network_mode: host