#!/bin/sh
#
# Generic package installer for the RTSProxy Synology package (DSM 6).

# define SYNOPKG_PKGVAR for compatibility with DSM7 (replaces former INST_VAR)
SYNOPKG_PKGVAR="${SYNOPKG_PKGDEST}/var"

# installer log is not writable, use for reference only.
INST_LOG="/var/log/packages/${SYNOPKG_PKGNAME}.log"

INST_ETC="/var/packages/${SYNOPKG_PKGNAME}/etc"
INST_VARIABLES="${INST_ETC}/installer-variables"

TMP_DIR="${SYNOPKG_TEMP_UPGRADE_FOLDER}/var"


install_log ()
{
    local _msg_="$@"
    if [ -z "${_msg_}" ]; then
        # read multiline from stdin
        while IFS=$'\n' read -r line; do
            install_log "${line}"
        done
    else
        # stderr goes to /var/log/packages/{package}.log
        # stdout goes to dialog in package manager ui.
        echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t${_msg_}" 1>&2
    fi
}

# Invoke shell function if available
call_func ()
{
    FUNC=$1
    if type "${FUNC}" 2>/dev/null | grep -q 'function' 2>/dev/null; then
        install_log "Begin ${FUNC}"
        LOG=$2
        if [ -z "${LOG}" ]; then
            eval ${FUNC}
        else
            eval ${FUNC} 2>&1 | ${LOG}
        fi
        install_log "End ${FUNC}"
    fi
}

# Source common installer helpers
INST_FUNCTIONS=`dirname $0`"/functions"
if [ -r "${INST_FUNCTIONS}" ]; then
    . "${INST_FUNCTIONS}"
fi

# Source package specific variables and functions
SVC_SETUP=`dirname $0`"/service-setup"
if [ -r "${SVC_SETUP}" ]; then
    . "${SVC_SETUP}"
fi

# Reload wizard variables stored by postinst
call_func "reload_inst_variables"


log_step ()
{
    install_log "===> Step $1. USER=$USER EFF_USER=$EFF_USER PORT=${SERVICE_PORT}"
}


# Remove the service user from the system
syno_remove_user ()
{
    RM_USER=$1
    if [ -n "${RM_USER}" ]; then
        if synouser --get "${RM_USER}" &> /dev/null; then
            echo "Removing user ${RM_USER}"
            synouser --del "${RM_USER}"
            synouser --rebuild all
            synogroup --rebuild all
        fi
    fi
}


# Set recursive permissions using chown
set_unix_permissions ()
{
    DIRNAME=$1
    if [ -n "${EFF_USER}" ]; then
        echo "Granting '${EFF_USER}' unix ownership on ${DIRNAME}"
        if [ "${SYNOPKG_DSM_VERSION_MAJOR}" -lt 6 ]; then
            chown -R ${EFF_USER}:root "${DIRNAME}"
        else
            chown -R ${EFF_USER}:${USER} "${DIRNAME}"
        fi
    fi
}


preinst ()
{
    log_step "preinst"
    call_func "service_preinst" install_log
    exit 0
}

postinst ()
{
    log_step "postinst"
    call_func "save_wizard_variables" install_log

    # Link for backward compatibility of the binaries location
    $LN "${SYNOPKG_PKGDEST}" "/usr/local/${SYNOPKG_PKGNAME}" 2>&1 | install_log

    # Link for DSM7 forward compatibility of the var location
    $LN "${SYNOPKG_PKGDEST}/var" "/var/packages/${SYNOPKG_PKGNAME}/var" 2>&1 | install_log

    $MKDIR "${SYNOPKG_PKGVAR}" 2>&1 | install_log

    call_func "service_postinst" install_log

    if [ -n "${LOG_FILE}" ]; then
        echo "Installation log: ${INST_LOG}" >> "${LOG_FILE}"
    fi

    # On DSM 6 only var is concerned
    set_unix_permissions "${SYNOPKG_PKGVAR}" 2>&1 | install_log

    exit 0
}

preuninst ()
{
    log_step "preuninst"
    call_func "service_preuninst" install_log
    exit 0
}

postuninst ()
{
    log_step "postuninst"

    if [ "${SYNOPKG_PKG_STATUS}" = "UNINSTALL" ]; then
        # Remove link
        $RM "/usr/local/${SYNOPKG_PKGNAME}" 2>&1 | install_log

        # Remove user
        syno_remove_user "${EFF_USER}" 2>&1 | install_log
    fi

    call_func "service_postuninst" install_log

    if [ "${SYNOPKG_PKG_STATUS}" = "UNINSTALL" ]; then
        $RM "${INST_VARIABLES}" 2>&1 | install_log
    fi
    exit 0
}

preupgrade ()
{
    log_step "preupgrade"
    call_func "service_preupgrade" install_log

    # Save the persistent data
    $RM "$TMP_DIR" 2>&1 | install_log
    $MKDIR "$TMP_DIR" 2>&1 | install_log

    call_func "service_save" install_log

    # Beware of /. outside the quotes: it copies hidden files too
    $CP "${SYNOPKG_PKGVAR}"/. "$TMP_DIR" 2>&1 | install_log
    exit 0
}

postupgrade ()
{
    log_step "postupgrade"

    call_func "service_restore" install_log

    # Restore the persistent data
    $CP "${TMP_DIR}"/. "${SYNOPKG_PKGVAR}" 2>&1 | install_log

    set_unix_permissions "${SYNOPKG_PKGVAR}" 2>&1 | install_log

    $RM "$TMP_DIR" 2>&1 | install_log

    call_func "service_postupgrade" install_log

    exit 0
}
